# Playback
SPACE cycle pause
MBTN_LEFT cycle pause

# Context menu
MBTN_RIGHT script-binding uosc/menu

# Seek
LEFT script-binding seek_feedback/back5
RIGHT script-binding uosc/hold-right
j script-binding seek_feedback/back10
l script-binding seek_feedback/forward10


################################
# Speed
################################

# Lua later


# Volume
UP add volume 5
DOWN add volume -5
m cycle mute


# Display
f cycle fullscreen
i script-binding stats/display-stats


# Subtitle
C cycle sub-visibility
g add sub-delay -0.1
h add sub-delay 0.1


# Playlist
n playlist-next
p playlist-prev


# Loop
r cycle loop-file


# Advanced
, frame-back-step
. frame-step
s screenshot
a ab-loop
b ab-loop
